services:
  # Service aplikasi Node.js
  app:
    build: .
    ports:
      - "8000:3000"
    environment:
      - MONGODB_URI=mongodb://user3:giggling-river-789@154.26.131.145:32017/user3_database?authSource=admin
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules

  # Service MongoDB
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

# Volume untuk menyimpan data MongoDB
volumes:
  mongo-data:
